name: Publish NyquistTools module to PowerShell Gallery
on:
  # Trigger workflow on push to main branch
#  push:
#    branches: [main]
    
  # Allow running this workflow manually  
  workflow_dispatch:
  
jobs:
  publish-nyquisttoolsmodule:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
        
      - name: Publish NyquistTools module to PSGallery
        shell: pwsh
        run: |
          Publish-Module -Path NyquistTools -NuGetApiKey ${{ secrets.PSGALLERYAPIKEY }} -Verbose
